language: node_js
node_js:
  - node
branches:
  only:
    - master
before_deploy:
  - npm run build
deploy:
  provider: npm
  cleanup: false
  email: worldschaos@gmail.com
  api_token:
    secure: ZPSvFxFfVZNGy+dsv2jl4tAdE7XxjGrFEDQuTxQZ4z5WtnX41VfXIQg19SCNYKfpkdXm7CTkfO4IBQLIl6gGmNjGZhEuyFrblIjvQ+8Vrd4eCEY1CqqqCUX7gc66guUgJVGHk9xb1xHas3ZLk0jqRS65frUkZmsMa2VdliTmMlovNXkAFZ68BahFnP4voBZ3m2QLJpFfvS0QirgqyLVSnxHRWSOn+BH5+AhdKqNcOnTuRg1QJPZ09KzhIjQ3dT7K33wCTe/HP/SCT7fzcQCiQNzzcgzIDzF1TFC3fBQKBEF0LaC/lYV7zLR7YpqjnHY2fXIK8OjnxQJ/JUCR5rkutWQ2yU96gWdRKCazT3lICrZBIbxES51aFAU0Ct9Lnsg3T4zWYPJQjc4CgpL9tyQ9le90NqxqbXich0QMvT7Aq1Je3OOA6S91VNTTgHGxcHO0bxX0RDZvvD5DeOkdbsYsZOBU+d6xWlbh08PzHNTxhv2RCXs4KTvq20xQ41ZrcV00mHcUkkSkO3DxLC8TH3eSHXxZHD4GUeXB7zEWxy2zfHENadUj4/VtvEwlh7LholRAeoSV8+dDJmhnGXEf1XWJaZteCxv5EIG9JRSRVeYVg3xaLtV0nD+lvWhV0Op7QRp2zN1yvDOSVQ5YwX2OXbcY2Ymdc4+TWckJomiIYoReHCM=
  on:
    tags: true
    repo: Shedevro/web-utils
after_deploy:
  - npm run coveralls
