name: CI Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CI git
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email 'worldschaos@gmail.com'
          git remote rm origin
          git remote add origin "https://$USER_NAME:$GITHUB_TOKEN@github.com/Shedevro/web-utils.git"
          git fetch
        env:
          USER_NAME: 'ci-worker'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Run lint
        run: npx lerna run lint

      - name: Run tests
        run: npx jest --coverageReporters=lcov

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: npx lerna publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
